### ISSUE TITLE
Implement Batch API Support

### ISSUE THREAD

**Issue by brandonblack** [twitterdev/twitter-ruby-ads-sdk#1]
**Changes Needed:**
- [ ] Implement TwitterAds::Campaign#batch method
- [ ] Implement TwitterAds::LineItem#batch method
- [ ] Implement TwitterAds::TargetingCriteria#batch method
- [ ] Ensure Error Support
- [ ] Test Coverage
- [ ] Documentation

**Related documentation:**
https://dev.twitter.com/ads/reference/post/batch/accounts/%3Aaccount_id/campaigns
https://dev.twitter.com/ads/reference/post/batch/accounts/%3Aaccount_id/line_items

**Comment by pratik60** [comment]
Any ideas why was this cancelled?

**Comment by msbukkuri** [comment]
@brandonblack anyone working on this?

**Comment by msbukkuri** [comment]
@brandonblack shouldn't this method be in the Account level? Since we are attempting to create a batch operation of campaigns and line_items at the account level.

In that sense, we would write all the tests in the account_spec.rb. Does that make sense? Any guidance would be helpful!

**Comment by msbukkuri** [comment]
@brandonblack any thoughts on the above questions? Guidance would be helpful.

**Comment by brandonblack** [comment]
There is unfortunately no active development happening on this, but if you're interested in helping build it let me know.

**Comment by msbukkuri** [comment]
@brandonblack I am interested, already started putting some thoughts together in these commits: 
https://github.com/msbukkuri/twitter-ruby-ads-sdk/commit/53272e11a4e31195213981034643a9ba49df0cbb

Just had this question:
- Shouldn't the batch method be in the Account level? Since we are attempting to create a batch operation of campaigns and line_items at the account level.

**Comment by jbabichjapan** [comment]
Closing this out - @msbukkuri please check this out and open up new Issues if you have any comments or problems (definitely would appreciate help banging against it and making sure it's solid)
