### ISSUE TITLE
Get all promoted tweets

### ISSUE THREAD

**Issue by igniting** [twitterdev/twitter-ruby-ads-sdk#114]
**Issue Type:** Feature

**Description:**

Currently there is no method to fetch all promoted tweets associated with an account. Twitter Ads api has this endpoint: https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/promoted_tweets There should be a method defined in [account.rb](https://github.com/twitterdev/twitter-ruby-ads-sdk/blob/master/lib/twitter-ads/account.rb) for fetching all promoted tweets.

**Comment by johnbabich** [comment]
Hi,

Please see the following function inside account.rb, is it what you were looking for?

    def promotable_tweets(id = nil, opts = {})

Thanks for your interest in this SDK.

**Comment by jbabichjapan** [comment]
Hi,

Please see the following function inside account.rb, is it what you were looking for?

def promotable_tweets(id = nil, opts = {})
Thanks for your interest in this SDK.

**Comment by igniting** [comment]
Oh yes. Should have looked more in code. Documentation is outdated: https://twitterdev.github.io/twitter-ruby-ads-sdk/reference/TwitterAds/Account.html
