### ISSUE TITLE
Implement Reach Estimate Support

### ISSUE THREAD

**Issue by brandonblack** [twitterdev/twitter-ruby-ads-sdk#12]
**Changes Needed:**
- [ ] Implement TwitterAds::ReachEstimate
- [ ] Test Coverage
- [ ] Documentation

**Related documentation:**
https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/reach_estimate

**Comment by brandonblack** [comment]
Recommend implementing this as a module that can't be instantiated similar to [TwitterAds::Placement](https://github.com/twitterdev/twitter-ruby-ads-sdk/blob/master/lib/twitter-ads/placement.rb).

**Comment by berndverst** [comment]
@AnSavvides I'm taking this over from you :)

**Comment by AnSavvides** [comment]
I can't believe you'd do that to me @berndverst :crying_cat_face:
