### ISSUE TITLE
Account and Funding Instruments not included in Analytics

### ISSUE THREAD

**Issue by bobintornado** [twitterdev/twitter-ruby-ads-sdk#120]
Feature

According to Ads Enumerations (https://dev.twitter.com/ads/basics/enums) page, there are five entities under Analytics, namely ACCOUNT, FUNDING_INSTRUMENT, CAMPAIGN, LINE_ITEM, PROMOTED_TWEET, ORGANIC_TWEET, but right now I assumed only three are supported in the lib.

Am I misunderstanding something or the feature simply is missing?

**Comment by brandonblack** [comment]
Somewhat related:
https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/105#issuecomment-241975110

Pulling stats at the Account and Funding Instrument are actually considered a bad practice. This will exhaust your rate limit quicker and require you to make additional, extraneous calls to re-fetch data for the same time period at a lower granularity. 

The official recommendation and best practice is to pull these stats at the promoted tweet or line item level and roll them up to a larger aggregation (account, funding instrument or campaign) as needed:

>Do request data (ideally) at the line_items and promoted_tweets level, as you can always aggregate and roll these metrics up to get totals across the entire ads entity hierarchy (i.e. for the campaign, funding instrument or account levels).

This approach will deliver the best performance the minimal number of calls required to fetch the maximum amount of Twitter Ads analytic data.

Prohibiting (or at least not supporting) pulling analytics at these levels was a deliberate design decision in the SDKs as it would encourage sub-optimal use of the API and lead to poor performance.

Related reading:
https://dev.twitter.com/ads/analytics/best-practices
