### ISSUE TITLE
Handle rate limit errors in TonUpload.

### ISSUE THREAD

**Issue by AlexCppns** [twitterdev/twitter-ruby-ads-sdk#123]
**Issue Type:**  Improvement 

**Description:**

Using TONUpload (from TailoredAudience.create) does not handle rate limiting. This means we have to restart from the beginning of the file every time we hit the limit. We have no control over the speed at which we upload chunks.

**Steps to Reproduce:**

```
file_name = '/tmp/200Megabytes.txt'
TailoredAudience.create(account, file_name, "Test", "EMAIL")
#=> TwitterAds::RateLimit
```

**Comment by jbabichjapan** [comment]
@AlexCppns Can you help us see if this issue still happens? I expect to be able to set a larger chunk size and with fast upload not hit rate limit

**Comment by jbabichjapan** [comment]
@AlexCppns I'm going to close this issue as I believe it is not as bad of a problem now that the min file size issue is fixed and trying to clean up to understand priority of things to do, please open another one if you find the usability to still be a problem.
