### ISSUE TITLE
Create an "Open Call" for Community Maintainers

### ISSUE THREAD

**Issue by brandonblack** [twitterdev/twitter-ruby-ads-sdk#130]
I'd like to propose that we open this project up to additional maintainers from the community. ✨ 

Once pull request approvals [are correctly enabled](https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/129), I'd love to see us give write access to our more active members of the community and establish a process for requesting a release to rubygems from the Twitter team.

My recommendations for potential maintainers (if they're willing):
- @alexsinger https://github.com/twitterdev/twitter-ruby-ads-sdk/commits?author=alexsinger
- @kambayashia https://github.com/twitterdev/twitter-ruby-ads-sdk/commits?author=kambayashia

---
CC: @jaakko-sf @jbabichjapan 
Depends On: twitterdev/twitter-ruby-ads-sdk#129

**Comment by bobintornado** [comment]
+1

**Comment by jbabichjapan** [comment]
Done! Thanks for getting it started
