### ISSUE TITLE
Previewing a status with spaces in it results in %20 in the rendered preview

### ISSUE THREAD

**Issue by scottmartinnet** [twitterdev/twitter-ruby-ads-sdk#138]
**Issue Type:** Bug

**Description:** When sending status text containing spaces to the API for a preview, the rendered preview contains %20s instead of spaces.  In https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/67, I provided a code change to stop this, but learned that the bug was actually in the API.  @brandonblack reported that the bug has been fixed, and I observed the code properly working and switched back to the master, but at some point since there was a regression and the server behavior went back to the wrong way again.

**Expected Result:**
"test test" is previewed as "test test"

**Actual Result:**
"test%20test" is previewed.

**Steps to Reproduce:**
- Send a string with spaces to the preview API.
- Observe the rendered preview.

**Relates To:** #67, #89

**Comment by jbabichjapan** [comment]
Sorry for delay, thanks for heads up about this @scottmartinnet I checked the Python SDK and it behaves well without this encoding so I guess it must have been added as a bandaid and can be removed now. We welcome open source contributions too so please feel free to keep pull requests coming. For now check the PR I just sent would love to hear if it works for you.

**Comment by smaeda-ks** [comment]
Closing this old issue as this is not a case anymore and preview API ([GET accounts/:account_id/tweet/preview](https://developer.twitter.com/en/docs/ads/creatives/api-reference/tweets#get-accounts-account-id-tweet-preview)) will no longer be available as of 2019-08-20. You can use `TweetPreview` class instead (documentation [here](https://developer.twitter.com/en/docs/ads/creatives/api-reference/tweet-previews)).
