### ISSUE TITLE
Uploading audiences greater than 1 megabyte fails consistently

### ISSUE THREAD

**Issue by scottmartinnet** [twitterdev/twitter-ruby-ads-sdk#139]
**Issue Type:** Bug

**Description:**
When uploading an audience file with a size greater than 1 megabyte, a crash is experienced.

**Expected Result:**
A valid audience is created.

**Actual Result:**
A crash is experienced:
#<TwitterAds::BadRequest:0x69944322762860 code=400 details="[{:code=>"INVALID_PARAMETER", :message=>"Expected valid file path, got \"/ta_partner/271491713/E1QTem1icxbUE5J.txt?resumable=true&resumeId=853413\" for input_file_path", :parameter=>"input_file_path"}]">

**Steps to Reproduce:**
Execute the following code with an ads account object and a filename of a file larger than 1 megabyte (1048576 bytes):
TwitterAds::TailoredAudience.create(account, '/path_to_file', "name", 'TWITTER_ID')

The actual contents of the file doesn't appear to matter, just that it's more than 1 megabyte, suggesting that the code in the API client intended to upload in 1 megabyte chunks is failing.

**Comment by jbabichjapan** [comment]
Have you tried to merge in the latest code? We actually made some changes intended to fix that problem but it hasn't been included in a release (working on preparing the next release right now)

**Comment by scottmartinnet** [comment]
I can confirm that this issue is fixed in the latest code.  Thanks for the help.
