### ISSUE TITLE
Implement App List Support

### ISSUE THREAD

**Issue by brandonblack** [twitterdev/twitter-ruby-ads-sdk#14]
**Changes Needed:**
- [x] Implement TwitterAds::AppList
- [x] Test Coverage
- [x] Documentation

**Related documentation:**
https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/app_lists
https://dev.twitter.com/ads/reference/post/accounts/%3Aaccount_id/app_lists
https://dev.twitter.com/ads/reference/get/accounts/%3Aaccount_id/app_lists/%3Aapp_list_id

**Comment by berndverst** [comment]
Possible follow-up items for @brandonblack:
- Need to check why app list names append Strings of form "@ 1234567899234" server side
- Handle the fact that app list does not provide a cursor
