### ISSUE TITLE
Api v2?

### ISSUE THREAD

**Issue by baldarn** [twitterdev/twitter-ruby-ads-sdk#160]
**Issue Type:** Question

**Description:**

Will this gem be updated to work with api v2?

**Comment by yosh1kura** [comment]
I am also wondering when it will be updated to version 2.

**Comment by kenta-s** [comment]
I got an email from Twitter today: 

> Reminder:
> Migrate to v2 of the Twitter Ads API
> 
> This is a reminder to migrate to v2 of the Twitter Ads API.
> 
> This release includes the ability to create and manage scheduled tweets, a new ad format—the video website card—for clickable video, additional draft campaign functionality, and an endpoint for retrieving summary information for asynchronous analytics jobs.
> View recommended specs under Video Website cards here.
> 
> Note: v1 will be turned off on January 10th, 2018.
>

**Comment by baldarn** [comment]
check this fork. The endpoint should be updated to V2

https://github.com/facehub/twitter-ruby-ads-sdk

**Comment by tushdante** [comment]
Hey @baldarn appreciate the work here! Would you mind making a pull request to this repo as well?
