### ISSUE TITLE
Unable to add start_time or end_time properties to line_item

### ISSUE THREAD

**Issue by jmarbach** [twitterdev/twitter-ruby-ads-sdk#178]
For example, when I try to assign the end_time property to a line_item, I see the following error:

`line_item.end_time = DateTime.now.tomorrow.strftime("%FT%Tz")`

```line_item.end_time = DateTime.now.tomorrow.strftime("%FT%Tz")
NoMethodError: undefined method `end_time=' for #<TwitterAds::LineItem:0x47374068722480 id="c8rkn">

**Comment by smaeda-ks** [comment]
@jmarbach This should be fixed in the next release. Thanks for pointing this out!
