### ISSUE TITLE
API v4 rubygem

### ISSUE THREAD

**Issue by qnm** [twitterdev/twitter-ruby-ads-sdk#183]
**Issue Type:**

Question

**Description:**

With the V3 sunset deadline approaching, I'd really like to see a release of this gem supporting V4. When will we see one?

Yes, we can reference the github repo directly, but would prefer to see an official rubygem release.

**Comment by osowskit** [comment]
@tushdante can you confirm this was resolved by https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/184?

**Comment by qnm** [comment]
Confirming I can see the V4 gem in rubygems.org now. Thanks, closing.

**Comment by qnm** [comment]
@osowskit Apologies, I missed this one:

https://github.com/twitterdev/twitter-ruby-ads-sdk/blob/master/lib/twitter-ads/client.rb#L6

This should also be updated to `4`.

**Comment by qnm** [comment]
Thanks @smaeda-ks - now we just need a minor version bump so rubygems packages up the new code!

**Comment by qnm** [comment]
Should be fixed by https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/187, testing now.
