### ISSUE TITLE
Why target_cpa_local_micro has been removed from TwitterAds::LineItem

### ISSUE THREAD

**Issue by bugcloud** [twitterdev/twitter-ruby-ads-sdk#208]
**Issue Type:** Question

**Description:**

`target_cpa_local_micro` has been removed from `TwitterAds::LineItem` in https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/193 .
I searched the reason on [Developers forum](https://twittercommunity.com/) and this project issues, but I cloud not find it. 

PR comment is

> I sorted property by name so the diff shows extra lines but FYI I simply just added:

🤔

**Comment by bugcloud** [comment]
@smaeda-ks I have a question to your merged [PR](https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/193). I want to know the reason If you have time.

**Comment by smaeda-ks** [comment]
Hey @bugcloud , thanks for flagging this. Probably. just my mistake. I'll fix it soon.

**Comment by bugcloud** [comment]
@smaeda-ks OK, I see.
Thank you for your quick response 🙏

**Comment by smaeda-ks** [comment]
Hey @bugcloud ,

After chatted with the team internally we confirmed that the `target_cpa_local_micro` field was deprecated a while ago and it shouldn't be used for any endpoint parameter nowadays.
(FYI, it used to be a parameter for `Website Conversions` objective which was gone [in 2017](https://twittercommunity.com/t/deprecation-announcement-website-conversions/83264))

That is, we may plan to remove this field from the response field of the Line Items endpoints entirely near the future and hence we've decided not to revert the change this time.

Let me know if you have any questions or please feel free to close this issue if that makes sense to you.

**Comment by bugcloud** [comment]
@smaeda-ks OK, I understand. Thank your for your announcement.
