### ISSUE TITLE
Implement GET accounts/:account_id/line_item_apps

### ISSUE THREAD

**Issue by Jave0722** [twitterdev/twitter-ruby-ads-sdk#216]
**Issue Type:** Improvement

**Description:**

There is no Implementation of `GET accounts/:account_id/line_item_apps`.

https://developer.twitter.com/en/docs/ads/campaign-management/api-reference/line-item-apps

**Comment by osowskit** [comment]
This endpoint is getting [deprecated mid-September](https://twittercommunity.com/t/announcement-breaking-changes-to-mobile-app-promotion-campaigns/140794) so is unnecessary. Users should set these on the line_item #228
