### ISSUE TITLE
Modification of response attributes in part of targeting options in api v6

### ISSUE THREAD

**Issue by Jave0722** [twitterdev/twitter-ruby-ads-sdk#217]
**Issue Type:** Improvement

**Description:**
In [Ads API version 6](https://twittercommunity.com/t/ads-api-version-6/129060), the following changes have been made to response attributes.
However, it does not seem to have changed.

Endpoint | v5 | v6
-- | -- | --
GET targeting_criteria/behavior_taxonomies | id | targeting_value
GET targeting_criteria/behaviors | id | targeting_value
GET targeting_criteria/devices | platform | os_type
GET targeting_criteria/events | id | targeting_value
GET targeting_criteria/platform_versions | platform | os_type
GET targeting_criteria/tv_markets | id | removed
GET targeting_criteria/tv_shows | id | targeting_value
| | | locale

**Comment by smaeda-ks** [comment]
Thanks! https://github.com/twitterdev/twitter-ruby-ads-sdk/pull/218
