### ISSUE TITLE
Support API version 9

### ISSUE THREAD

**Issue by koki-miyazaki** [twitterdev/twitter-ruby-ads-sdk#242]
**Issue Type:** Feature

**Description:**

Version 8 is going EOL on August 31, 2021: https://developer.twitter.com/en/docs/twitter-ads-api/versioning

A list of changes: https://twittercommunity.com/t/ads-api-version-9/150316

**Comment by koki-miyazaki** [comment]
python library was updated
https://github.com/twitterdev/twitter-python-ads-sdk/releases/tag/v9.0.0

**Comment by billgathen** [comment]
Updated gem is live on rubygems as of July 16, 2021.

[https://rubygems.org/gems/twitter-ads](https://rubygems.org/gems/twitter-ads)
