### ISSUE TITLE
Improve Test Coverage for Account to 100%

### ISSUE THREAD

**Issue by msbukkuri** [twitterdev/twitter-ruby-ads-sdk#93]
**Issue Type:** Improvement

**Description:** 
scoped_timeline and authenticated_user_access can use a test.
Please see details here: https://codeclimate.com/github/twitterdev/twitter-ruby-ads-sdk/coverage/573f548192f884000103177c

**Comment by brandonblack** [comment]
See https://github.com/twitterdev/twitter-ruby-ads-sdk/issues/99#issuecomment-220808518
