### ISSUE TITLE
Improve Test Coverage for Targeting Criteria to 100%

### ISSUE THREAD

**Issue by msbukkuri** [twitterdev/twitter-ruby-ads-sdk#95]
**Issue Type:** Improvement

**Description:** 
Please see details here: https://codeclimate.com/github/twitterdev/twitter-ruby-ads-sdk/coverage/573f548192f8840001031783

**Comment by brandonblack** [comment]
See https://github.com/twitterdev/twitter-ruby-ads-sdk/issues/99#issuecomment-220808518
